### ISSUE TITLE
What am I doing wrong?!

### ISSUE THREAD

**Issue by cgrattonUW** [giovannicoppola/zothero#11]
Hi Folks-

I loved the ZotHero workflow when it worked, but then it stopped working a few months back. I've now updated Alfred to 5.0.3 and am using the last version of ZotHero (1.99.7). The workflow is installed, and it starts to work as I type in the search bar, when I type "zot" it seems to start working, but then it switches to google search as soon as I give it any text.  It gives this error in the Debugger window:

[13:21:18.553] ERROR: ZotHero[Script Filter] Code 1: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

Any ideas?

Thanks!

**Comment by lutefiasco** [comment]
Posted this in alfredforums - try re-loading the Command Line Developer Tools (in terminal, 
xcode-select --install) fixed the issue.

**Comment by cgrattonUW** [comment]
Brilliant!  Why didn't I ask earlier - many thanks!
