### ISSUE TITLE
Cannot open an item in Zotero properly

### ISSUE THREAD

**Issue by u2003** [giovannicoppola/zothero#12]
Hello, I don't know what happened with the workflow after I switched to Alfred 5. Every time I try to type enter or fn + enter after searching in Zothero, it just fails to open the item selected in Zotero. And something quite strange would happen, when I try to switch to another app at this time, the Zotero would always jumps to the front. (As you can see in the video) 

![CleanShot_2022-11-08_15 05 35](https://user-images.githubusercontent.com/84957135/200497301-6d10f3c8-484a-444e-bcaf-02bfae26de14.gif)

And here is the debug info:

[Debug info of ZotHero.txt](https://github.com/giovannicoppola/zothero/files/9958606/Debug.info.of.ZotHero.txt)

Thank you so much!

**Comment by giovannicoppola** [comment]
consolidating with the other issue
