### ISSUE TITLE
Cannot copy bibliography properly

### ISSUE THREAD

**Issue by u2003** [giovannicoppola/zothero#13]
It's kind of like the situation that I mentioned on the last post. When I press option+enter on an item, nothing would be copied, and it would jump to the Finder, which is quite strange.(You can see that in the video) I would be so grateful if you could please tell me what's going wrong.

![CleanShot_2022-11-08_15 16 42](https://user-images.githubusercontent.com/84957135/200499254-34d9b3c8-780d-476a-a209-e7d03fa574a8.gif)

[Debug info of Zothero-fail to copy bibliography.txt](https://github.com/giovannicoppola/zothero/files/9958645/Debug.info.of.Zothero-fail.to.copy.bibliography.txt)

**Comment by giovannicoppola** [comment]
did you change the zotero directory?  what is your current path to it?

**Comment by u2003** [comment]
Thank you for your reply! Yeah, I change the path from ~/Zotero to ~/Documents/Zotero

**Comment by u2003** [comment]
That's because I use iCloud to backup and synchronize my Zotero directory

**Comment by giovannicoppola** [comment]
HI, unfortunately I can't reproduce this. Could you try the most recent version and send me the log file? The one you shared before was empty.
