### ISSUE TITLE
Changing Style Doesn't Work

### ISSUE THREAD

**Issue by lutefiasco** [giovannicoppola/zothero#14]
Alfred 5.0.5, Zothero v. 2.0, Mac OS 13.0.1

Using the 2.0 build, selecting a style in zotconf fails silently. Restarting and reloading Zotero data doesn't change.

Running the debugger isn't showing anything:
Initial state - 
 {
      "title": "Default Style: Chicago Manual of Style 17th edition (author-date)",
      "subtitle": "\u21a9 to change style",
      "valid": true,
      "variables": {
        "action": "choose-style",
        "varname": "CITE_STYLE",
        "style": "http://www.zotero.org/styles/chicago-author-date"
      },

But then, running it

11:00:59 config.py:89 DEBUG    [config] attachdir='/Users/USER/Box Sync'
11:00:59 config.py:86 DEBUG    [config] datadir='/Users/USER/Zotero'
11:00:59 core.py:72 DEBUG    [core] cachedir='~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/giovanni-zothero'
11:00:59 core.py:73 DEBUG    [core] zotero_dir='~/Zotero'
11:00:59 core.py:74 DEBUG    [core] attachments_dir='~/Box Sync'
11:00:59 zh.py:645 DEBUG    [settings] setting "CITE_STYLE" to "http://www.zotero.org/styles/chicago-fullnote-bibliography" ...
11:00:59 workflow.py:1483 DEBUG    reading settings from /Users/USER/Library/Application Support/Alfred/Workflow Data/giovanni-zothero/settings.json
11:00:59 workflow.py:2314 DEBUG    set last run version: 2.0.0
11:00:59 workflow.py:2136 DEBUG    ---------- finished in 0.202s ----------
[11:00:59.393] ZotHero[Run Script] Processing complete
[11:00:59.397] ZotHero[Run Script] Passing output '{
  "items": []
}' to Call External Trigger
[11:00:59.401] ZotHero[External] Processing complete
[11:00:59.405] ZotHero[External] Passing output '' to Run Script
[11:00:59.409] ZotHero[Run Script] Passing output '{
  "items": []
}' to Filter
[11:00:59.413] ZotHero[Filter] Processing complete
[11:00:59.416] ZotHero[Filter] Passing output '{
  "items": []
}' to Call External Trigger
[11:00:59.419] ZotHero[External] Processing complete
[11:00:59.422] ZotHero[External] Passing output '' to Script Filter
[11:00:59.426] ZotHero[Script Filter] Queuing argument ''
[11:00:59.526] STDERR: ZotHero[Run Script] .

**Comment by Korean-David** [comment]
I'm having the same issue.

**Comment by lutefiasco** [comment]
A temporary work around:  click "Configure workflow" in Alfred preferences, and manually paste the zotero style repository URL there (https://www.zotero.org/styles).

**Comment by giovannicoppola** [comment]
The style is not refreshed immediately in `zotconf` (need to rerun it to see it updated) but it is changed. Could you send me the actual steps, or a short screencast so I can reproduce?

**Comment by lutefiasco** [comment]
It wasn't a matter of re-running zotconf, but it seemed as if the alfred preferences weren't sticking? Can't reproduce anymore, and seems resolved.
