### ISSUE TITLE
error with bib

### ISSUE THREAD

**Issue by cgrattonUW** [giovannicoppola/zothero#18]
I installed the ZotHero 2.1 version appropriate for Alfred 5. But I seem to get an error with saying:

[Errno2] No such file or directory: '/Users/me/Zotero/better-bibtex.sqlite'

I am using the default path for Zotero since that is where I have installed it.  I am sure I have some setting wrong.

Thanks,
Claudio

**Comment by giovannicoppola** [comment]
@cgrattonUW I think you need to install the `better-bibtex` add-on in Zotero. Instructions [here](https://retorque.re/zotero-better-bibtex/installation)
