### ISSUE TITLE
NoneType not subscriptable

### ISSUE THREAD

**Issue by macrospecter** [giovannicoppola/zothero#20]
This worked well for me for a couple of days, but now I'm getting an error regarding "NoneType." Any idea what might have broken the workflow? 

TypeError: 'NoneType' object is not subscriptable
22:48:57 workflow.py:2116 INFO     for assistance, see: https://github.com/giovannicoppola/zothero/issues
22:48:57 workflow.py:2136 DEBUG    ---------- finished in 0.136s ----------
[22:48:58.094] ZotHero[Script Filter] {
  "items": [
    {
      "title": "Error in workflow 'ZotHero'",
      "subtitle": "'NoneType' object is not subscriptable",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"

**Comment by macrospecter** [comment]
Ah, for others who might have the same issue, I found the answer: I corrected by opening zotconf in the dialog box and selecting Reload Zotero Data. Thanks again for the plugin.

**Comment by laffan** [comment]
Thanks @macrospecter ! ( @giovannicoppola  I humbly suggest this be put in the Readme. It happens every few days for me.)
