### ISSUE TITLE
database locked error

### ISSUE THREAD

**Issue by jterning** [giovannicoppola/zothero#27]
worked once and then:
![Untitled](https://github.com/giovannicoppola/zothero/assets/660555/6ce59c65-80ca-4b30-9a10-5801db2a8243)
database is locked

**Comment by giovannicoppola** [comment]
probably Zotero was open while the database was being rebuilt. Can you try again after closing Zotero?

**Comment by joshuadanpeterson** [comment]
Got the same error. Tried again after closing Zotero and still got the message.

Edit: It worked again after clicking on Zotero Configuration and then Reload Zotero Data.
