### ISSUE TITLE
Changing enviroment variables has no effect

### ISSUE THREAD

**Issue by SamuelAcunaPhD** [giovannicoppola/zothero#9]
Changing the environment variables to this workflow do not seem to change the behaviour of the workflow. for example, even if I set the ZOTERO_DIR to a different path, it still only searches the default path. Also, if I set a value for the COPY_CITEKEY_MOD it does not change the function of the modifier keys.

**Comment by olivierroymd** [comment]
> Changing the environment variables to this workflow do not seem to change the behaviour of the workflow. for example, even if I set the ZOTERO_DIR to a different path, it still only searches the default path. Also, if I set a value for the COPY_CITEKEY_MOD it does not change the function of the modifier keys.

Same for me.

**Comment by pkumath** [comment]
> Changing the environment variables to this workflow do not seem to change the behaviour of the workflow. for example, even if I set the ZOTERO_DIR to a different path, it still only searches the default path. Also, if I set a value for the COPY_CITEKEY_MOD it does not change the function of the modifier keys.

Same here, cannot use COPY_CITEKEY_MOD.
